rule:


    cnr_society_and_environment_major:
        description: "Society and Environment Major"
        rule: AND
        args:
            - rule: university_all
            - rule: cnr_lowerdiv_society_requirements
            - rule: cnr_upperdiv_society_requirements
            - rule: cnr_units_upperdiv
            - rule: units_upperdiv
            - rule: units_total



    cnr_lowerdiv_society_requirements:
        description: "Lower Division Society and Environment Requirement"
        rule: AND
        args:
            - rule: cnr_society_math
            - rule: econ_lowerdiv
            - rule: cnr_society_breadth

    cnr_society_math:
        hidden: true
        rule: OR
        args:
            - course: MATH.1A
            - course: MATH.10A
            - course: MATH.16A
            - course: STAT.2
            - course: STAT.20
            - course: PB HLTH.140
            - course: PB HLTH.142

    cnr_society_breadth:
        hidden: true
        rule: count_courses
        args:
            min: 7
            rule: AND
            args:
                - rule: cnr_breadth_arts_history_philosophy
                - rule: ls_breadth_physical
                - rule: ls_breadth_biological
                - rule: ls_breadth_international
                - rule: ls_breadth_social
                - rule: cnr_espm_environmental_science_core
                - rule: cnr_espm_social_science_core


    cnr_upperdiv_society_requirements:
        description: "Upper Division Society and Environment Requirements"
        rule: AND
        args:
            - rule: cnr_environmental_political_economics_requirement
            - rule: cnr_concentration_society_requirements
            - course: ESPM.194B


    cnr_environmental_political_economics_requirement:
        description: "Environmental or Political Economics Requirement"
        rule: OR
        args:
            - course: POL SCI.126A
            - course: POL SCI.139B
            - course: GEOG.C110
            - course: GEOG.C112
            - course: GEOG.156
            - course: DEV STD.C100
            - course: ECON.C125
            - course: ENVECON.100
            - course: ENVECON.C101
            - course: ENVECON.131
            - course: ENVECON.140AC
            - course: ENVECON.153
            - course: ENVECON.161
            - course: ENVECON.C180
            - course: ENE,RES.C180
            - course: ISF.C101
            - course: POLECON.100
            - course: POLECON.101
            - course: GPP.115
            - course: IAS.115
            - course: PUB POL.C103

    cnr_concentration_society_requirements:
        description: "Society and Environment Concentrations: US Environmental Policy and Management, Global Environmental Politics, Justice and Sustainability"
        rule: OR
        args:
            - rule: cnr_concentration_society_us
            - rule: cnr_concentration_society_global
            - rule: cnr_concentration_society_justice

    cnr_concentration_society_us:
        description: "Society and Environment Concentrations: US Environmental Policy and Management"
        rule: count_courses
        args:
            min: 7
            rule: AND
            args:
                - rule: society_us_primary
                - rule: society_us_electives
                - rule: society_us_other

    society_us_primary:
        hidden: true
        rule: OR
        args:
            - course: ESPM.102C
            - course: ESPM.102D
            - course: ESPM.160AC
            - course: ESPM.161
            - course: ESPM.186
            - course: ESPM.C191

    society_us_electives:
        hidden: true
        rule: count_courses
        args:
            min: 4
            rule: cnr_society_and_environment_area_us_environmental_policy_and_management

    society_us_other:
        hidden: true
        rule: count_courses
        args:
            min: 3
            rule: OR
            args:
                - rule: cnr_society_and_environment_area_global_environmental_politics
                - rule: cnr_society_and_environment_area_justice_and_sustainability

    cnr_concentration_society_global:
        description: "Society and Environment Concentrations: Global Environmental Policy"
        rule: count_courses
        args:
            min: 7
            rule: AND
            args:
                - rule: society_global_primary
                - rule: society_global_electives
                - rule: society_global_other

    society_global_primary:
        hidden: true
        rule: OR
        args:
            - course: ESPM.151
            - course: ESPM.162
            - course: ESPM.165
            - course: ESPM.168
            - course: ESPM.169

    society_global_electives:
        hidden: true
        rule: count_courses
        args:
            min: 4
            rule: cnr_society_and_environment_area_global_environmental_politics

    society_global_other:
        hidden: true
        rule: count_courses
        args:
            min: 4
            rule: OR
                - rule: cnr_society_and_environment_area_us_environmental_policy_and_management
                - rule: cnr_society_and_environment_area_justice_and_sustainability


    cnr_concentration_society_justice:
        description: "Society and Environment Concentrations: Justice and Sustainability"
        rule: count_courses
        args:
            min: 7
            rule: AND
            args:
                - rule: society_justice_primary
                - rule: society_justice_electives
                - rule: society_justice_other

    society_justice_primary:
        hidden: true
        rule: OR
        args:
            - course: ESPM.117
            - course: ESPM.155
            - course: ESPM.163AC
            - course: ESPM.166
            - course: ESPM.C167

    society_justice_electives:
        hidden: true
        rule: count_courses
        args:
            min: 4
            rule: cnr_society_and_environment_area_justice_and_sustainability

    society_justice_other:
        hidden: true
        rule: count_courses
        args:
            min: 3
            rule: OR
            args:
                - rule: cnr_society_and_environment_area_us_environmental_policy_and_management
                - rule: cnr_society_and_environment_area_global_environmental_politics


    cnr_society_and_environment_area_us_environmental_policy_and_management:
        description: "Society & Environment US Environmental Policy and Management Area of Concentration"
        rule: same_course
        args:
            - OR:
                - course: AMERSTD.C172
                - course: UGBA.107
                - course: UGBA.C172
                - course: CY PLAN.110
                - course: CY PLAN.112A
                - course: CY PLAN.113A
                - course: CY PLAN.113B
                - course: CY PLAN.118AC
                - course: ENE,RES.C100
                - course: ENE,RES.170
                - course: ENE,RES.175
                - course: ENE,RES.C180
                - course: ENVECON.C102
                - course: ENVECON.C118
                - course: ENVECON.151
                - course: ENVECON.152
                - course: ENVECON.153
                - course: ENVECON.162
                - course: ESPM.102C
                - course: ESPM.102D
                - course: ESPM.160AC
                - course: ESPM.161
                - course: ESPM.186
                - course: ESPM.C191
                - course: GEOG.103
                - course: GEOG.C110
                - course: GEOG.130
                - course: HISTORY.120AC
                - course: HISTORY.122AC
                - course: HISTORY.124A
                - course: HISTORY.135
                - course: ISF.C101
                - course: LEGALST.100
                - course: LEGALST.141
                - course: LEGALST.145
                - course: LEGALST.147
                - course: LEGALST.176
                - course: LEGALST.178
                - course: POL SCI.113B
                - course: POL SCI.114A
                - course: POL SCI.161
                - course: PUB POL.C103
                - course: PUB POL.C184
                - course: SOCIOL.110
                - course: SOCIOL.131AC
                - course: SOCIOL.144AC
                - course: SOCIOL.145AC
                - course: SOCIOL.186

    cnr_society_and_environment_area_global_environmental_politics:
        description: "Society & Environment Global Environmental Politics Area of Concentration"
        rule: same_course
        args:
            - OR:
                - course: AFRICAM.131
                - course: ANTHRO.137
                - course: ANTHRO.139
                - course: EDUC.186AC
                - course: ESPM.151
                - course: ESPM.162
                - course: ESPM.165
                - course: ESPM.168
                - course: ESPM.169
                - course: ETH STD.159AC
                - course: ENVECON.131
                - course: GWS.141
                - course: GEOG.130
                - course: GEOG.137
                - course: GEOG.138
                - course: GEOG.159AC
                - course: IAS.102
                - course: LEGALST.140
                - course: LEGALST.179
                - course: LEGALST.182
                - course: POL SCI.120A
                - course: POL SCI.127A
                - course: POL SCI.138E
                - course: POL SCI.139D
                - course: RHETOR.107
                - course: SOCIOL.102
                - course: SOCIOL.127

    cnr_society_and_environment_area_justice_and_sustainability:
        description: "Society & Environment Justice and Sustainability Area of Concentration"
        rule: same_course
        args:
            - OR:
                - course: ESPM.117
                - course: ESPM.155
                - course: ESPM.163AC
                - course: ESPM.166
                - course: ESPM.C167
                - course: DEV STD.C100
                - course: GWS.130AC
                - course: GEOG.C112
                - course: HISTORY.135
                - course: LD ARCH.130
                - course: LEGALST.100
                - course: LEGALST.103
                - course: LEGALST.107
                - course: LEGALST.187
                - course: NATAMST.100
                - course: NATAMST.104
                - course: POL SCI.124C
                - course: PB HLTH.C160
                - course: SOCIOL.128
                - course: SOCIOL.138AC
                - course: SOCIOL.183
                - course: SOCIOL.145AC




