rules: # not sure if I should combine lower/upper div into one concentration, since math split from rest


    cnr_molecular_environmental_biology_major:
        description: "Molecular Environmental Biology Major"
        rule: AND
        args:
            - rule: university_all
            - rule: cnr_lowerdiv_molecular_environmental_requirements
            - rule: cnr_biological_core_molecular_environmental_requirements
            - rule: cnr_lab_molecular_environmental_requirement
            - rule: cnr_concentration_molecular_environmental_requirement
            - rule: cnr_units_upperdiv
            - rule: units_upperdiv
            - rule: units_total



    cnr_lowerdiv_molecular_environmental_requirements:
        description: "Lower Division Molecular Environmental Biology Requirements"
        rule: AND
        args:
            - course: CHEM.1A
            - course: CHEM.1AL
            - course: CHEM.3A
            - course: CHEM.3AL
            - course: CHEM.3B
            - course: CHEM.3BL
            - course: BIOLOGY.1A
            - course: BIOLOGY.1AL
            - course: BIOLOGY.1B
            - course: PHYSICS.8A
            - rule: cnr_es_breadth

    cnr_biological_core_molecular_environmental_requirements:
        description: "Biological Core Molecular Environmenal Biology Requirements"
        rule: count_courses
        args:
            min: 7
            rule: AND
            args:
                - rule: meb_biochem
                - rule: meb_mb
                - rule: meb_cell
                - rule: meb_physiology
                - rule: meb_diversity
                - rule: meb_ecology
                - rule: meb_seminar

    meb_biochem:
        hidden: true
        rule: OR
        args:
            - course: MCELLBI.102
            - course: CHEM.135
            - course: MCELLBI.110

    meb_mb:
        hidden: true
        rule: OR
        args:
            - course: INTEGBI.141
            - course: INTEGBI.161
            - course: INTEGBI.162
            - course: INTEGBI.164
            - course: MCELLBI.104
            - course: MCELLBI.110
            - course: MCELLBI.140
            - course: PLANTBI.160

    meb_cell:
        hidden: true
        rule: OR
        args:
            - course: MCELLBI.130
            - course: MCELLBI.130A
            - course: MCELLBI.133L
            - course: MCELLBI.135E
            - course: MCELLBI.137
            - course: MCELLBI.141
            - rule: mcbc112
            - rule: pmbc112
            - course: PB HLTH.162A

    meb_physiology:
        hidden: true
        rule: OR
        args:
            - course: ESPM.144
            - course: INTEGBI.132
            - course: INTEGBI.140
            - course: INTEGBI.148
            - course: MCELLBI.136
            - course: NUSCTX.103
            - course: PLANTBI.C116
            - course: MCELLBI.C116
            - course: PLANTBI.135

    meb_diversity:
        hidden: true
        rule: OR
        args:
            - course: ESPM.106
            - course: ESPM.108A
            - course: ESPM.115B
            - course: ESPM.132
            - course: ESPM.C138
            - course: PLANTBI.C114
            - course: MCELLBI.C114
            - rule: pmbc112
            - rule: mcbc112
            - course: ESPM.140
            - rule: ibc101
            - rule: ib102
            - rule: ib103
            - rule: ib104
            - rule: ib168
            - rule: pmbc102
            - rule: pmb110
            - course: PLANTBI.113
            - course: PLANTBI.C116
            - course: MCELLBI.C116
            - rule: pmb120
            - AND:

    meb_ecology:
        hidden: true
        rule: OR
        args:
            - course: ESPM.102A
            - course: ESPM.110
            - course: ESPM.111
            - course: ESPM.112
            - course: ESPM.113
            - course: ESPM.114
            - course: ESPM.115C
            - rule: espm116
            - course: ESPM.119
            - course: ESPM.131
            - course: ESPM.C149
            - course: INTEGBI.C149
            - course: INTEGBI.153
            - rule: ib154

    espm116:
        hidden: true
        rule: OR
        args:
            - course: ESPM.116A
            - course: ESPM.116B
            - course: ESPM.116C

    meb_seminar:
        hidden: true
        rule: OR
        args:
            - course: ESPM.192
            - course: PLANTBI.170

    cnr_lab_molecular_environmental_requirement:
        description: "Molecular Environmental Biology Lab Requirement"
        rule: count_courses
        args:
            min: 2
            rule: OR
            args:
                - course: ANTHRO.135
                - course: MCELLBI.133L
                - course: INTEGBI.101L
                - course: INTEGBI.102L
                - course: INTEGBI.103L
                - course: INTEGBI.104L
                - course: INTEGBI.N116
                - course: INTEGBI.117L
                - course: INTEGBI.131L
                - course: INTEGBI.154L
                - course: INTEGBI.164
                - course: INTEGBI.168L
                - course: INTEGBI.173L
                - course: INTEGBI.174L
                - course: INTEGBI.175L
                - course: INTEGBI.183L
                - course: INTEGBI.184L
                - course: PLANTBI.C102L
                - course: PLANTBI.110L
                - course: PLANTBI.C112L
                - course: PLANTBI.113
                - course: PLANTBI.120L
                - course: ESPM.102A
                - course: ESPM.105
                - course: ESPM.106
                - course: ESPM.108A
                - course: ESPM.115C
                - course: ESPM.117
                - course: ESPM.132
                - course: ESPM.140
                - course: ESPM.146L
                - course: ESPM.147 # x 3
                - course: PB HLTH.162L
                - rule: meb_lab_other

    meb_lab_other:
        hidden: true
        rule: OR
        args:
            - course: ESPM.105A
            - course: ESPM.C107 # 4 only
            - course: INTEGBI.C158 # 4 only
            - course: GEOG.C142 # 4 only
            - course: ESPM.H196
            - course: ESPM.199
            - course: NSCTX.H196
            - course: NSCTX.199
            - course: PLANTBI.H196
            - course: PLANTBI.199

    cnr_concentration_molecular_environmental_requirement:
        description: "Molecular Environmental Biology Concentrations: Animal Health & Behavior, Biodiversity, Ecology, Environment & Human Health, Insect Biology, and Microbiology"
        rule: same_course
        args:
            - OR:
                - rule: cnr_concentration_molecular_environmental_animal_health
                - rule: cnr_concentration_molecular_environmental_biodiversity
                - rule: cnr_concentration_molecular_environmental_ecology
                - rule: cnr_concentration_molecular_environmental_environment_human_health
                - rule: cnr_concentration_molecular_environmental_insect_biology
                - rule: cnr_concentration_molecular_environmental_microbiology

    cnr_concentration_molecular_environmental_animal_health:
        description: "Molecular Environmental Biology Concentration: Animal Health & Behavior"
        rule: AND
        args:
            - rule: math_a
            - rule: math_b
            - rule: meb_animal_health_courses

    meb_animal_health_courses:
        hidden: true
        rule: units
        args:
            min: 12
            rule: OR
            args:
                - course: ANTHRO.135
                - course: ESPM.C103
                - course: INTEGBI.C156
                - course: ESPM.106
                - course: ESPM.110
                - course: ESPM.114
                - course: ESPM.C126
                - course: IB.C144
                - course: PSYCH.C115B
                - course: ESPM.C142
                - course: ESPM.145
                - course: ESPM.146
                - course: ESPM.146L
                - course: ESPM.186
                - course: ESPM.188
                - rule: ib104
                - course: INTEGBI.C143A
                - course: PSYCH.C113
                - course: INTEGBI.C143B
                - course: PSYCH.C116
                - course: INTEGBI.146
                - course: INTEGBI.148
                - rule: ib184
                - course: INTEGBI.186
                - course: PSYCH.121

    cnr_concentration_molecular_environmental_biodiversity:
        description: "Molecular Environmental Biology Concentration: Biodiversity"
        rule: AND
        args:
            - rule: math_a
            - rule: meb_math_b
            - rule: meb_biodiversity_courses

    meb_math_b:
        hidden: true
        rule: OR
        args:
            - course: MATH.1B
            - course: MATH.16B
            - course: STAT.2
            - course: STAT.20
            - course: STAT.25
            - course: PB HLTH.142A
            - course: STAT.131A

    meb_biodiversity_courses:
        hidden: true
        rule: units
        args:
            min: 12
            rule: OR
            args:
                - course: ESPM.105
                - course: ESPM.106
                - course: ESPM.108A
                - course: ESPM.115B
                - course: ESPM.132
                - course: ESPM.140
                - course: ESPM.147
                - rule: ibc101
                - rule: ib102
                - rule: ib103
                - rule: ib104
                - course: INTEGBI.160
                - course: INTEGBI.166
                - rule: ib168
                - rule: ib174
                - rule: ib174
                - rule: ib175
                - course: INTEGBI.183
                - course: INTEGBI.183L
                - rule: pmbc102
                - rule: pmb110
                - course: PLANTBI.113
                - course: PLANTBI.C116
                - course: MCELLBI.C116
                - rule: pmb120

    espmc103_ibc156:
        hidden: true
        rule: OR
        args:
            - course: ESPM.C103
            - course: INTEGBI.C156

    cnr_concentration_molecular_environmental_ecology:
        description: "Molecular Environmental Biology Concentration: Ecology"
        rule: AND
        args:
            - rule: math_a
            - rule: meb_math_b
            - rule: meb_ecology_courses

    meb_ecology_courses:
        hidden: true
        rule: units
        args:
            min: 12
            rule: OR
            args:
                - course: ESPM.105A
                - course: ESPM.102A
                - course: ESPM.C103
                - course: INTEGBI.C156
                - course: ESPM.111
                - course: ESPM.112
                - course: ESPM.113
                - course: ESPM.114
                - course: ESPM.115B
                - course: ESPM.115C
                - course: ESPM.116B
                - course: ESPM.116C
                - course: ESPM.117
                - course: ESPM.118
                - course: ESPM.119
                - course: ESPM.C139
                - course: GEOG.C136
                - course: ESPM.131
                - course: ESPM.134
                - rule: espm146
                - course: ESPM.147
                - course: ESPM.C149
                - course: INTEGBI.C149
                - course: ESPM.152
                - course: ESPM.172
                - course: ESPM.173
                - course: ESPM.174
                - course: ESPM.C180
                - course: ESPM.181
                - course: ESPM.188
                - course: PLANTBI.180
                - rule: ib102
                - course: INTEGBI.151
                - course: INTEGBI.153
                - rule: ib154
                - course: INTEGBI.C155
                - course: ANTHRO.C129D

    cnr_concentration_molecular_environmental_environment_human_health:
        description: "Molecular Environmental Biology Concentration: Environment & Human Health"
        rule: AND
        args:
            - rule: math_a
            - rule: math_b
            - rule: meb_human_courses

    meb_human_courses:
        hidden: true
        rule: units
        args:
            min: 12
            rule: OR
            args:
                - course: ANTHRO.135
                - course: ESPM.C126
                - course: INTEGBI.C144
                - course: PSYCH.C115B
                - course: ESPM.C138
                - course: PLANTBI.C114
                - course: MCELLBI.C114
                - course: ESPM.145
                - course: ESPM.146L
                - course: ESPM.C148
                - course: NUSCTX.C159
                - course: ESPM.162
                - course: ESPM.167
                - course: INTEGBI.N116
                - course: INTEGBI.117
                - course: INTEGBI.117L
                - course: INTEGBI.131
                - course: INTEGBI.131L
                - course: INTEGBI.137
                - course: INTEGBI.140
                - course: INTEGBI.C143A
                - course: INTEGBI.C144A
                - course: PSYCH.C113
                - course: PSYCH.C116
                - course: MCELLBI.135
                - course: MCELLBI.150
                - course: MCELLBI.165
                - course: NUSCTX.103
                - course: NUSCTX.108A
                - course: NUSCTX.110
                - course: NUSCTX.C119
                - course: NUSCTX.160
                - course: NUSCTX.166
                - course: PLANTBI.C103
                - course: PLANTBI.C103
                - course: PLANTBI.180
                - course: PB HLTH.103
                - course: PB HLTH.104A
                - course: PB HLTH.104B
                - course: PB HLTH.105
                - course: PB HLTH.114
                - course: PB HLTH.116
                - course: PB HLTH.150B
                - course: PSYCH.110

    cnr_concentration_molecular_environmental_insect_biology:
        description: "Molecular Environmental Biology Concentration: Insect Biology / Anthropod Science"
        rule: AND
        args:
            - course: ESPM.140
            - rule: math_a
            - rule: meb_math_b

    meb_insect_courses:
        hidden: true
        rule: units
        args:
            min: 8
            rule: OR
            args:
                - course: ESPM.105
                - course: ESPM.113
                - course: ESPM.115B
                - course: ESPM.132
                - course: ESPM.134
                - course: ESPM.140
                - course: ESPM.142
                - course: ESPM.144
                - course: ESPM.145
                - rule: espm146
                - course: ESPM.147
                - course: ESPM.148

    cnr_concentration_molecular_environmental_microbiology:
        description: "Molecular Environmental Biology Concentration: Microbiology"
        rule: AND
        args:
            - rule: math_a
            - rule: math_b
            - rule: meb_microbiology_courses

    meb_microbiology_courses:
        hidden: true
        rule: units
        args:
            min: 12
            rule: OR
            args:
                - course: CHM ENG.114
                - course: ESPM.112
                - course: ESPM.131
                - course: ESPM.C138
                - course: PLANTBI.C114
                - course: MCELLBI.C114
                - course: MCELLBI.113
                - course: MCELLBI.C148
                - course: PLANTBI.C103
                - course: MCELLBI.C103
                - course: PB HLTH.C102
                - course: PLANTBI.C112
                - course: MCELLBI.C112
                - course: PLANTBI.C112L
                - course: MCELLBI.C112L
                - course: PLANTBI.C116
                - course: MCELLBI.C116
                - course: PB HLTH.162A
                - course: PB HLTH.162L 

